name: Update Feeds
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main  # or master, depending on your default branch
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Debug file structure
        run: |
          pwd
          ls -la
          ls -la src/
      
      - name: Install deps
        run: npm ci
      
      - name: Install Playwright
        run: npx playwright install chromium --with-deps
      
      - name: Generate feeds
        run: npm start
        env:
          PINTEREST_EMAIL: ${{ secrets.PINTEREST_EMAIL }}
          PINTEREST_PASSWORD: ${{ secrets.PINTEREST_PASSWORD }}
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public