name: Update Feeds

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

env:
  PINTEREST_SESSION_RAIYAN: ${{ secrets.PINTEREST_SESSION_RAIYAN }}
  PINTEREST_SESSION_ZARIN: ${{ secrets.PINTEREST_SESSION_ZARIN }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browser (if needed)
        run: |
          if [ ! -d ~/.cache/ms-playwright ]; then
            npx playwright install chromium --with-deps
          fi
      
      - name: Generate feeds
        run: |
          export DEBUG=pw:api
          NODE_OPTIONS="--max-old-space-size=4096" npm start
      
      # Upload debug screenshots
      - name: Upload debug screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: debug-screenshots/
          retention-days: 5
      
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true