name: Update Feeds

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browser (if needed)
        run: |
          if [ ! -d ~/.cache/ms-playwright ]; then
            npx playwright install chromium --with-deps
          fi
      
      - name: Generate feeds
        run: |
          # Enable more verbose logging
          export DEBUG=pw:api
          # Run with increased timeouts
          NODE_OPTIONS="--max-old-space-size=4096" npm start
        env:
          PINTEREST_EMAIL: ${{ secrets.PINTEREST_EMAIL }}
          PINTEREST_PASSWORD: ${{ secrets.PINTEREST_PASSWORD }}
          DEBUG: pw:api  # Enable Playwright debug logging
      
      # Upload screenshots even if the previous step fails
      - name: Upload debug screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: debug-screenshots/
          retention-days: 5
      
      # Upload logs for debugging
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            *.log
            npm-debug.log*
          retention-days: 5
      
      - name: Deploy
        if: success()  # Only deploy if previous steps succeeded
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true